### PR TITLE
Admin Configuration Page

### PR DESCRIPTION
**Pull request by Miley-Afful**
https://www.loom.com/share/0235a66b46f04f7691dab68873dce7c3?sid=da949c8e-3e90-4d94-8c18-b332985b0447  
                                                                                                                                                                 https://www.loom.com/share/be099a1ad1814aca999bae5520355f65?sid=3b0c4769-ff72-4d63-9291-b512ae246c08

### CODE REVIEW

**Comment by Miley-Afful** [comment]
Waiting for review

**Comment by Miley-Afful** [comment]
waiting for review

**Comment by muchinon** [comment]
Screenshot 2024-11-10 212250

@Miley-Afful  There were 2 configurations when you expanded, so it should display '2' when not expanded. It should only show '0' when there are no configurations at all.

**Comment by Miley-Afful** [comment]
@muchinon, thanks for drawing my attention to that. please the changes have been made and committed

**Pull request merged**
