### PR TITLE
added the routing to the user details

### PR DESCRIPTION
**Pull request by Jhacy456**
https://www.loom.com/share/60f809b1927f4948b66afdea440e44da?sid=60694ed9-d36e-45de-ae35-2c18dc8f6493

### CODE REVIEW

**Comment by alexboateng** [comment]
@Jhacy456 Kindly check the UI and implement the other components on the page.
It has 2 tabs 
1. API Keys
2. Reported numbers
3. There is no New fraudulent number button in the UI given
Review the UI design to implement the changes

**Comment by Jhacy456** [comment]
> @Jhacy456 Kindly check the UI and implement the other components on the page. It has 2 tabs
> 
> 1. API Keys
> 2. Reported numbers
> 3. There is no New fraudulent number button in the UI given
>    Review the UI design to implement the changes

Alright I will do that

**Comment by Jhacy456** [comment]
https://www.loom.com/share/58949bd5572c4fdd87f8315d893f30db?sid=9bbd022a-fe45-40e2-92a2-afc6432d8faf

**Comment by Jhacy456** [comment]
> @Jhacy456 Kindly check the UI and implement the other components on the page. It has 2 tabs
> 
> 1. API Keys
> 2. Reported numbers
> 3. There is no New fraudulent number button in the UI given
>    Review the UI design to implement the changes

I have done the necessary corrections.

**Comment by alexboateng** [comment]
Great

**Pull request merged**
