### PR TITLE
displayed list of all reported numbers

### PR DESCRIPTION
**Pull request by odeifuo44**
@alexboateng For your review please. I was able to make an api call to display all reported numbers at the front end. Here is a brief recording of what i did: https://www.loom.com/share/5e8ac0f59f2143a5beb7da6dc5d0fddc?sid=edf23ce7-27d1-4551-8b6b-19f0a09f5ad7

### CODE REVIEW

**Comment by alexboateng** [comment]
@odeifuo44 Your PR is deleting a lot of files kindly check and create a new PR and tag the issue you are working on here

**Comment by odeifuo44** [comment]
Oh really? well noted. Pls should I do something else before creating a new PR?

**Comment by alexboateng** [comment]
You can create a new PR

**Comment by odeifuo44** [comment]
Hi good evening Alex. Pls I'm having a challenge creating a new PR. My
branch doesn't show to enable me create the request

**Pull request closed without merging**
