### PR TITLE
done working on the UI for the API Keys

### PR DESCRIPTION
**Pull request by MsBaidoo**

### CODE REVIEW

**Comment by alexboateng** [comment]
Add loom video

**Comment by MsBaidoo** [comment]
@alexboateng please find below the link to the loom video
https://www.loom.com/share/9dae1f4da166443dac90b12a15d9ef7a?sid=c332d90b-2664-451b-96c3-0a68430771cf

**Comment by alexboateng** [comment]
Loom video should show UI in browser as well

**Comment by MsBaidoo** [comment]
@alexboateng please find below loom video

https://www.loom.com/share/63ebf7d8e9e945ea844ba43ec977fd55?sid=50390c90-589c-4305-bae0-d773bd4288e9

**Pull request merged**
