### PR TITLE
Delete report

### PR DESCRIPTION
**Pull request by VidaOwusu**
Delete report has been worked on

Kindly find attached the link to the loom video
https://www.loom.com/share/91817528ddff4830bd4c09ef493d89cf?sid=dab7b190-0b24-4948-986e-e88cdcf53221

### CODE REVIEW

**Comment by alexboateng** [comment]
There are conflicts. Resolve these conflicts

**Comment by VidaOwusu** [comment]
Conflicts have been resolved

**Comment by alexboateng** [comment]
Conflicts still exists. Pull current changes into your branch

**Comment by VidaOwusu** [comment]
conflicts have been resolved

**Pull request merged**
